apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app1
  namespace: java-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  java-app
  template:
    metadata:
      labels:
        app:  java-app
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  java-application
        image: sandy01.jfrog.io/sandy-docker/java-project1:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"
