apiVersion: v1
kind: Service
metadata:
  name:  java-app-service
  namespace: java-proj
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000